# Generated by Django 5.0.6 on 2024-06-28 08:00

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='منطقه و محله ملک')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.PositiveIntegerField(verbose_name='طبقه')),
            ],
            options={
                'verbose_name': 'طبقه',
                'verbose_name_plural': 'طبقه ها',
            },
        ),
        migrations.CreateModel(
            name='Metr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrazh', models.CharField(max_length=100, verbose_name='رنج متراژ')),
            ],
            options={
                'verbose_name': 'متر',
                'verbose_name_plural': 'متراژ',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'قیمت',
                'verbose_name_plural': 'قیمت ها',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_home', models.PositiveIntegerField(verbose_name='تعداد اتاق')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(max_length=50, verbose_name='نوع معامله ملک')),
            ],
            options={
                'verbose_name': 'نوع معامله',
                'verbose_name_plural': 'نوع معاملات',
            },
        ),
        migrations.CreateModel(
            name='TypeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_house', models.CharField(max_length=100, verbose_name='نوع ملک')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'نوع املاک',
            },
        ),
        migrations.CreateModel(
            name='Melk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_seller', models.CharField(max_length=200, null=True, verbose_name='نام فروشنده')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن فروشنده')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.area', verbose_name='منطقه/محله')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.floor', verbose_name='طبقه')),
                ('metr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.metr', verbose_name='متراژ')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.price')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.room', verbose_name='اتاق')),
                ('trade_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.tradetype', verbose_name='نوع معامله')),
                ('type_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.typehouse', verbose_name='نوع ملک')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to)),
                ('melk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlaki.melk')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
