# Generated by Django 5.0.6 on 2024-06-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField(verbose_name='منطقه و محله ملک')),
            ],
            options={
                'verbose_name': 'منطقه',
                'verbose_name_plural': 'منطقه ها',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.PositiveIntegerField(verbose_name='رنج متراژ')),
            ],
            options={
                'verbose_name': 'تعداد اتاق',
                'verbose_name_plural': 'تعداد اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='Melk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
            },
        ),
        migrations.CreateModel(
            name='Metr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrazh', models.PositiveIntegerField(verbose_name='رنج متراژ')),
            ],
            options={
                'verbose_name': 'متر',
                'verbose_name_plural': 'متراژ',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_home', models.PositiveIntegerField(verbose_name='تعداد اتاق')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='TradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(max_length=50, verbose_name='نوع معامله ملک')),
            ],
            options={
                'verbose_name': 'نوع معامله',
                'verbose_name_plural': 'نوع معاملات',
            },
        ),
        migrations.CreateModel(
            name='TypeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_house', models.CharField(max_length=100, verbose_name='نوع ملک')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'نوع املاک',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('melk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlaki.melk')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
