# Generated by Django 5.0.6 on 2024-06-04 08:59

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlaki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'طبقه', 'verbose_name_plural': 'طبقه ها'},
        ),
        migrations.AddField(
            model_name='melk',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.area', verbose_name='منطقه/محله'),
        ),
        migrations.AddField(
            model_name='melk',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.floor', verbose_name='طبقه'),
        ),
        migrations.AddField(
            model_name='melk',
            name='full_name_seller',
            field=models.CharField(max_length=200, null=True, verbose_name='نام فروشنده'),
        ),
        migrations.AddField(
            model_name='melk',
            name='metr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.metr', verbose_name='متراژ'),
        ),
        migrations.AddField(
            model_name='melk',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تلفن فروشنده'),
        ),
        migrations.AddField(
            model_name='melk',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.room', verbose_name='اتاق'),
        ),
        migrations.AddField(
            model_name='melk',
            name='trade_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.tradetype', verbose_name='نوع معامله'),
        ),
        migrations.AddField(
            model_name='melk',
            name='type_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amlaki.typehouse', verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floors',
            field=models.PositiveIntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='melk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
