# Generated by Django 5.0.6 on 2024-06-28 08:00

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlaki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='melk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
