# Generated by Django 5.0.6 on 2024-06-04 09:10

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlaki', '0002_alter_floor_options_melk_area_melk_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melk',
            name='price',
            field=models.CharField(max_length=250, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='melk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
    ]
