# Generated by Django 5.0.6 on 2024-06-04 09:36

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlaki', '0003_melk_price_alter_gallery_image_alter_melk_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='melk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='metr',
            name='metrazh',
            field=models.CharField(max_length=100, verbose_name='رنج متراژ'),
        ),
    ]
